name: CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: "Install dependencies from package-lock.json"
        run: npm ci
      - name: "Lint"
        run: npm run lint
      - name: "test"
        run: npm run test:unit
      - name: "Upload code coverage to codecov.io"
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          verbose: true
